const quotes = [
    "You have the right to perform your prescribed duties, but you are not entitled to the fruits of your actions. (Bhagavad Gita 2.47)",
    "The soul is neither born, nor does it die; it is eternal and indestructible. (Bhagavad Gita 2.20)",
    "A person is said to be established in self-realization and is called a yogi when he is fully satisfied by virtue of transcendental knowledge and wisdom. (Bhagavad Gita 6.20)",
    "Perform your duty equipoised, O Arjuna, abandoning all attachment to success or failure. (Bhagavad Gita 2.48)",
    "Pleasure and pain, gain and loss, victory and defeat—these are the dualities of life. (Bhagavad Gita 2.48)",
    "He who is unattached to the external world can truly enjoy life. (Bhagavad Gita 5.10)",
    "The mind is everything. What you think, you become. (Bhagavad Gita 6.6)",
    "What is night for all beings is the time of awakening for the sage who is awake. (Bhagavad Gita 2.69)",
    "There is neither happiness nor sadness in this world; everything is the result of your actions. (Bhagavad Gita 4.14)",
    "In this world, there is nothing so sublime and pure as transcendental knowledge. (Bhagavad Gita 4.38)",
    "Change is the law of the universe. (Bhagavad Gita 2.14)",
    "To relinquish all attachment to the results of action is the ultimate freedom. (Bhagavad Gita 3.19)",
    "One who is self-controlled and unattached is unaffected by sinful action, as the lotus flower is untouched by water. (Bhagavad Gita 5.10)",
    "Those who are not disturbed by the dualities of happiness and distress and are unbothered by those who are, are certainly eligible for liberation. (Bhagavad Gita 14.22)",
    "You came empty-handed, and you will leave empty-handed. (Bhagavad Gita 5.29)",
    "The true essence of the self is beyond fear and doubt. (Bhagavad Gita 6.5)",
    "He who has faith has wisdom; he who does not have faith is ignorant. (Bhagavad Gita 4.39)",
    "One who has controlled the mind is a true yogi. (Bhagavad Gita 6.6)",
    "The wise see all beings in themselves, and themselves in all beings. (Bhagavad Gita 6.29)",
    "The soul is eternal; it transcends the physical realm. (Bhagavad Gita 2.20)",
    "The greatest service is to inspire others to serve. (Bhagavad Gita 3.19)",
    "Your thoughts create your reality; think wisely. (Bhagavad Gita 6.5)",
    "He who is not disturbed by the world is truly wise. (Bhagavad Gita 6.8)",
    "Wisdom is knowing the right path to take; integrity is taking it. (Bhagavad Gita 2.31)",
    "Life is a battle, and you must fight. (Bhagavad Gita 2.47)",
    "The greatest wealth is to live content with little. (Bhagavad Gita 4.22)",
    "One who has no faith in himself can never have faith in God. (Bhagavad Gita 3.16)",
    "Joy is the natural state of the soul. (Bhagavad Gita 6.27)",
    "Surrender is not weakness; it is strength in acceptance. (Bhagavad Gita 18.66)",
    "Your only limit is you. (Bhagavad Gita 6.5)",
    "Every experience is an opportunity for learning. (Bhagavad Gita 6.35)",
    "Do not dwell in the past; do not dream of the future, concentrate the mind on the present moment. (Bhagavad Gita 6.5)",
    "What you think, you become. What you feel, you attract. What you imagine, you create. (Bhagavad Gita 6.6)",
    "Service to others is the greatest service of all. (Bhagavad Gita 3.19)",
    "Detach from the outcome; focus on the action. (Bhagavad Gita 4.20)",
    "The only way you can truly be at peace is by relinquishing your desire for recognition. (Bhagavad Gita 5.13)",
    "What you seek is seeking you. (Bhagavad Gita 4.42)",
    "Courage is not the absence of fear but the triumph over it. (Bhagavad Gita 18.15)",
    "Let your heart guide your actions. (Bhagavad Gita 16.3)",
    "You are the creator of your destiny; take charge. (Bhagavad Gita 6.6)",
    "Everything you can imagine is real. (Bhagavad Gita 9.32)",
    "Trust the timing of your life. (Bhagavad Gita 4.39)",
    "Every moment is a fresh beginning. (Bhagavad Gita 3.19)",
    "You are what you believe you are. (Bhagavad Gita 6.34)",
    "True happiness comes from within; nurture your inner self. (Bhagavad Gita 2.62)",
    "You have the power to choose your own destiny. (Bhagavad Gita 18.16)",
    "Happiness is not something you postpone for the future; it is something you design for the present. (Bhagavad Gita 12.15)",
    "To change the world, you must first change yourself. (Bhagavad Gita 6.25)",
    "Life is about making an impact, not making an income. (Bhagavad Gita 2.14)",
    "With every heartbeat, you have the chance to make a difference. (Bhagavad Gita 3.20)",
    "You are the artist of your own life; don’t hand the paintbrush to anyone else. (Bhagavad Gita 3.19)",
    "Let your actions speak for your intentions. (Bhagavad Gita 3.16)",
    "Everything has beauty, but not everyone sees it. (Bhagavad Gita 18.16)",
    "Your life is a reflection of your thoughts. (Bhagavad Gita 6.6)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 18.20)",
    "The secret of change is to focus all of your energy, not on fighting the old, but on building the new. (Bhagavad Gita 4.16)",
    "Every setback is a setup for a comeback. (Bhagavad Gita 2.47)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 4.42)",
    "Mistakes are proof that you are trying. (Bhagavad Gita 2.64)",
    "Let your dreams be bigger than your fears. (Bhagavad Gita 6.5)",
    "Focus on what you can do, not what you can't. (Bhagavad Gita 5.10)",
    "Strive for progress, not perfection. (Bhagavad Gita 3.17)",
    "The greatest service is to inspire others to serve. (Bhagavad Gita 3.19)",
    "Seek the truth, and the truth will set you free. (Bhagavad Gita 4.36)",
    "You create your own reality with your thoughts. (Bhagavad Gita 6.6)",
    "Your thoughts are the architects of your destiny. (Bhagavad Gita 6.5)",
    "In the middle of difficulty lies opportunity. (Bhagavad Gita 2.47)",
    "Everything you can imagine is real. (Bhagavad Gita 9.32)",
    "True strength is being able to maintain your balance amidst chaos. (Bhagavad Gita 5.20)",
    "Believe in the power of your dreams. (Bhagavad Gita 4.39)",
    "Let go of your fears and embrace your potential. (Bhagavad Gita 6.5)",
    "Through self-discipline, you can achieve anything. (Bhagavad Gita 6.34)",
    "Every action you take is a step towards your future. (Bhagavad Gita 2.30)",
    "In a gentle way, you can shake the world. (Bhagavad Gita 12.13)",
    "Believe you can and you're halfway there. (Bhagavad Gita 3.19)",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. (Bhagavad Gita 4.39)",
    "Hardships often prepare ordinary people for an extraordinary destiny. (Bhagavad Gita 5.13)",
    "You are capable of amazing things. (Bhagavad Gita 6.25)",
    "The only limit to our realization of tomorrow will be our doubts of today. (Bhagavad Gita 6.6)",
    "Let your passion be your guide. (Bhagavad Gita 3.19)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "You have the potential to achieve greatness. (Bhagavad Gita 6.25)",
    "Success is not the key to happiness. Happiness is the key to success. (Bhagavad Gita 2.50)",
    "You are the master of your own destiny. (Bhagavad Gita 18.66)",
    "The future belongs to those who believe in the beauty of their dreams. (Bhagavad Gita 2.47)",
    "Your soul is beyond the material body; embrace your true self. (Bhagavad Gita 2.20)",
    "Everything you seek is seeking you. (Bhagavad Gita 4.42)",
    "The power of love is greater than the power of fear. (Bhagavad Gita 12.13-14)",
    "True wealth is the richness of the heart. (Bhagavad Gita 3.19)",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. (Bhagavad Gita 18.66)",
    "Simplicity is the ultimate sophistication. (Bhagavad Gita 3.30)",
    "Doubt kills more dreams than failure ever will. (Bhagavad Gita 2.50)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "It's not whether you get knocked down; it's whether you get up. (Bhagavad Gita 2.47)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.20)",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. (Bhagavad Gita 6.6)",
    "Life is what happens when you’re busy making other plans. (Bhagavad Gita 18.20)",
    "You are the hero of your own story. (Bhagavad Gita 2.47)",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. (Bhagavad Gita 18.67)",
    "Do what you can, with what you have, where you are. (Bhagavad Gita 2.47)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Strive not to be a success, but rather to be of value. (Bhagavad Gita 3.19)",
    "Life isn't about finding yourself. Life is about creating yourself. (Bhagavad Gita 2.50)",
    "Don’t count the days; make the days count. (Bhagavad Gita 2.14)",
    "Happiness is a direction, not a place. (Bhagavad Gita 5.10)",
    "Success usually comes to those who are too busy to be looking for it. (Bhagavad Gita 3.17)",
    "Opportunities don't happen. You create them. (Bhagavad Gita 4.42)",
    "It does not matter how slowly you go as long as you do not stop. (Bhagavad Gita 6.5)",
    "Everything you’ve ever wanted is on the other side of fear. (Bhagavad Gita 6.34)",
    "Act with a sense of purpose; every action has meaning. (Bhagavad Gita 4.39)",
    "The best time to plant a tree was 20 years ago. The second best time is now. (Bhagavad Gita 2.47)",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. (Bhagavad Gita 6.5)",
    "The mind is a wonderful servant but a terrible master. (Bhagavad Gita 6.6)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Don’t wait for opportunity. Create it. (Bhagavad Gita 6.5)",
    "Dream big and dare to fail. (Bhagavad Gita 6.6)",
    "If you can dream it, you can do it. (Bhagavad Gita 2.50)",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. (Bhagavad Gita 2.50)",
    "You are stronger than you think. (Bhagavad Gita 6.6)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Great things are not done by impulse, but by a series of small things brought together. (Bhagavad Gita 3.19)",
    "Life is 10% what happens to us and 90% how we react to it. (Bhagavad Gita 2.48)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Success is walking from failure to failure with no loss of enthusiasm. (Bhagavad Gita 3.19)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 3.16)",
    "The greatest discovery of my generation is that a human being can alter his life by altering his attitude. (Bhagavad Gita 6.5)",
    "The mind is the root of all suffering and all happiness. (Bhagavad Gita 2.14)",
    "Do not be embarrassed by your failures; learn from them and start again. (Bhagavad Gita 3.19)",
    "You have the power to change your life; you just have to want it badly enough. (Bhagavad Gita 6.25)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "Every day may not be good, but there is something good in every day. (Bhagavad Gita 6.20)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "You must expect great things of yourself before you can do them. (Bhagavad Gita 2.50)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Opportunities are usually disguised as hard work, so most people don't recognize them. (Bhagavad Gita 6.20)",
    "You have the right to work, but never to the fruit of your work. (Bhagavad Gita 2.47)",
    "Do not let what you cannot do interfere with what you can do. (Bhagavad Gita 3.17)",
    "Change your thoughts and you change your world. (Bhagavad Gita 6.34)",
    "Keep your face always toward the sunshine—and shadows will fall behind you. (Bhagavad Gita 4.20)",
    "We are what we repeatedly do. Excellence, then, is not an act but a habit. (Bhagavad Gita 3.19)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Do not wait to strike till the iron is hot, but make it hot by striking. (Bhagavad Gita 3.19)",
    "What we achieve inwardly will change outer reality. (Bhagavad Gita 6.20)",
    "Act with integrity and kindness; the world needs more of both. (Bhagavad Gita 3.19)",
    "You are not here merely to make a living. You are here to enable the world to live more amply. (Bhagavad Gita 4.14)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "You cannot swim for new horizons until you have courage to lose sight of the shore. (Bhagavad Gita 6.6)",
    "The best way to predict the future is to create it. (Bhagavad Gita 2.47)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success usually comes to those who are too busy to be looking for it. (Bhagavad Gita 6.20)",
    "Happiness is not something ready-made. It comes from your own actions. (Bhagavad Gita 2.47)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "To live is the rarest thing in the world. Most people exist, that is all. (Bhagavad Gita 6.6)",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. (Bhagavad Gita 6.5)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Our lives begin to end the day we become silent about things that matter. (Bhagavad Gita 18.67)",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. (Bhagavad Gita 6.34)",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. (Bhagavad Gita 2.47)",
    "We cannot solve our problems with the same thinking we used when we created them. (Bhagavad Gita 6.34)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "You can’t connect the dots looking forward; you can only connect them looking backwards. (Bhagavad Gita 3.19)",
    "Success is not how far you got, but the height you achieved. (Bhagavad Gita 4.14)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "Don’t count the days; make the days count. (Bhagavad Gita 2.50)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Act with a sense of purpose; every action has meaning. (Bhagavad Gita 4.39)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Life is not about finding yourself. Life is about creating yourself. (Bhagavad Gita 2.50)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Our greatest glory is not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "The best revenge is massive success. (Bhagavad Gita 3.19)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Success is not how far you got, but the height you achieved. (Bhagavad Gita 4.14)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Do not let what you cannot do interfere with what you can do. (Bhagavad Gita 3.17)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Act with integrity and kindness; the world needs more of both. (Bhagavad Gita 3.19)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Happiness is a direction, not a place. (Bhagavad Gita 5.10)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "The future belongs to those who believe in the beauty of their dreams. (Bhagavad Gita 2.47)",
    "Dream big and dare to fail. (Bhagavad Gita 6.6)",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. (Bhagavad Gita 6.34)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. (Bhagavad Gita 6.5)",
    "Act with a sense of purpose; every action has meaning. (Bhagavad Gita 4.39)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. (Bhagavad Gita 6.5)",
    "Everything you seek is seeking you. (Bhagavad Gita 4.42)",
    "Do not wait to strike till the iron is hot, but make it hot by striking. (Bhagavad Gita 3.19)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "You are the master of your own destiny. (Bhagavad Gita 18.66)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "You are not here merely to make a living. You are here to enable the world to live more amply. (Bhagavad Gita 4.14)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. (Bhagavad Gita 18.67)",
    "Everything you’ve ever wanted is on the other side of fear. (Bhagavad Gita 6.34)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. (Bhagavad Gita 6.34)",
    "Your soul is beyond the material body; embrace your true self. (Bhagavad Gita 2.20)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "You have the power to change your life; you just have to want it badly enough. (Bhagavad Gita 6.25)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Believe in yourself and all that you are. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Do not let what you cannot do interfere with what you can do. (Bhagavad Gita 3.17)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. (Bhagavad Gita 2.47)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. (Bhagavad Gita 18.67)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "You can’t connect the dots looking forward; you can only connect them looking backwards. (Bhagavad Gita 3.19)",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. (Bhagavad Gita 6.34)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "Happiness is a direction, not a place. (Bhagavad Gita 5.10)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Act with integrity and kindness; the world needs more of both. (Bhagavad Gita 3.19)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Life is not about finding yourself. Life is about creating yourself. (Bhagavad Gita 2.50)",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. (Bhagavad Gita 6.34)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Everything you seek is seeking you. (Bhagavad Gita 4.42)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "You can’t connect the dots looking forward; you can only connect them looking backwards. (Bhagavad Gita 3.19)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. (Bhagavad Gita 6.34)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Believe in yourself and all that you are. (Bhagavad Gita 2.50)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "You can’t connect the dots looking forward; you can only connect them looking backwards. (Bhagavad Gita 3.19)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Happiness is a direction, not a place. (Bhagavad Gita 5.10)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Believe in yourself and all that you are. (Bhagavad Gita 2.50)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "You can’t connect the dots looking forward; you can only connect them looking backwards. (Bhagavad Gita 3.19)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "Believe in yourself and all that you are. (Bhagavad Gita 2.50)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "Believe in yourself and all that you are. (Bhagavad Gita 2.50)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Success is the sum of small efforts, repeated day in and day out. (Bhagavad Gita 4.39)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Believe in yourself and all that you are. (Bhagavad Gita 2.50)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Success is not how high you have climbed, but how you make a positive difference to the world. (Bhagavad Gita 3.19)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. (Bhagavad Gita 2.14)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful. (Bhagavad Gita 2.47)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "You are what you believe yourself to be. (Bhagavad Gita 2.50)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Your time is limited, so don’t waste it living someone else’s life. (Bhagavad Gita 2.50)",
    "The greatest weapon against stress is our ability to choose one thought over another. (Bhagavad Gita 2.48)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.20)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "The purpose of our lives is to be happy. (Bhagavad Gita 2.50)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Believe you can, and you’re halfway there. (Bhagavad Gita 3.19)",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. (Bhagavad Gita 6.5)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Happiness is not the absence of conflict, but the ability to cope with it. (Bhagavad Gita 2.48)",
    "The future depends on what you do today. (Bhagavad Gita 2.47)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Act as if what you do makes a difference. It does. (Bhagavad Gita 4.39)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "The only way to do great work is to love what you do. (Bhagavad Gita 4.39)",
    "Life is really simple, but we insist on making it complicated. (Bhagavad Gita 5.29)",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. (Bhagavad Gita 2.50)",
    "Take time to deliberate, but when the time for action comes, stop thinking and go in. (Bhagavad Gita 2.50)",
    "Your life is your message to the world; make it inspiring. (Bhagavad Gita 6.35)",
    "What we fear doing most is usually what we most need to do. (Bhagavad Gita 2.50)",
    "You must be the change you wish to see in the world. (Bhagavad Gita 18.66)",
    "Take risks: if you win, you will be happy; if you lose, you will be wise. (Bhagavad Gita 6.34)",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. (Bhagavad Gita 3.19)",
    "Success is how high you bounce when you hit bottom. (Bhagavad Gita 3.19)",
    "Your best teacher is your last mistake. (Bhagavad Gita 4.14)",
    "Life is either a daring adventure or nothing at all. (Bhagavad Gita 4.)"

   
];function getRandomIndex() {
    return Math.floor(Math.random() * quotes.length);
}

let currentIndex = Math.random() * quotes.length;

function displayQuote() {
    const quoteElement = document.getElementById('t1');
    if (quoteElement) {
        quoteElement.innerHTML = `"${quotes[currentIndex]}"`;
    }
}

// Function to display the previous quote
function previousQuote() {
    if (currentIndex > 0) {
        currentIndex--;
    } else {
        currentIndex = quotes.length - 1; // Loop back to the last quote
    }
    displayQuote();
}

// Function to display the next quote
function nextQuote() {
    if (currentIndex < quotes.length - 1) {
        currentIndex++;
    } else {
        currentIndex = 0; // Loop back to the first quote
    }
    displayQuote();
}

function showToaster() {
    const toaster = document.getElementById("toaster");
    if (toaster) {
        toaster.classList.add("show");
        setTimeout(() => {
            toaster.classList.remove("show");
        }, 3000); // Toaster visible for 3 seconds
    }
}

// Combined window.onload to handle both the random quote display and the toaster
window.onload = () => {
    currentIndex = getRandomIndex(); // Get a random quote index
    displayQuote(); // Display the quote
    showToaster();  // Show the toaster notification
};
