const oshoQuotes = [
    "Be — don't try to become.",
    "Life begins where fear ends.",
    "Truth is not something outside to be discovered, it is something inside to be realized.",
    "Only those who are ready to become nobodies are able to love.",
    "Each person comes into this world with a specific destiny — he has something to fulfill, some message has to be delivered, some work has to be completed. You are not here accidentally — you are here meaningfully. There is a purpose behind you.",
    "Don't seek, don't search, don't ask, don't knock, don't demand — relax. If you relax, it comes. If you relax, it is there. If you relax, you start vibrating with it.",
    "A certain darkness is needed to see the stars.",
    "Falling in love you remain a child; rising in love you mature.",
    "Life should not only be lived, it should be celebrated.",
    "Love is the goal; life is the journey.",
    "Don't be afraid of experience, because the more experience you have, the more mature you become.",
    "Take hold of your own life. See that the whole existence is celebrating.",
    "Sadness gives depth. Happiness gives height. Sadness gives roots. Happiness gives branches. Happiness is like a tree going into the sky, and sadness is like the roots going down into the womb of the earth.",
    "You become that which you think you are.",
    "Don't try to force anything. Let life be a deep let-go.",
    "Don't move the way fear makes you move. Move the way love makes you move. Move the way joy makes you move.",
    "Tomorrow never comes, it is always today.",
    "Life is a balance between rest and movement.",
    "The less people know, the more stubbornly they know it.",
    "What is discipline? Discipline means creating an order within you.",
    "Get out of your head and get into your heart. Think less, feel more.",
    "Truth is not something outside to be discovered, it is something inside to be realized.",
    "Love is not about possession. Love is about appreciation.",
    "Experience life in all possible ways — good-bad, bitter-sweet, dark-light, summer-winter.",
    "Don't look for the meaning of life. Simply live it.",
    "Love cannot be taught. It can only be caught.",
    "The greatest fear in the world is the opinion of others.",
    "The moment you become innocent, you have found a direct line to the divine.",
    "To avoid pain, they avoid pleasure. To avoid death, they avoid life.",
    "You feel good, you feel bad, and these feelings are bubbling from your own unconsciousness, from your own past. Nobody is responsible except you.",
    "Freedom is the ultimate value in the world of consciousness.",
    "Happiness has nothing to do with success, happiness has nothing to do with ambition, happiness has nothing to do with money, power, prestige. It is a totally different dimension.",
    "The only thing that matters in life, is your own opinion about yourself.",
    "The whole world is nothing but a mirror.",
    "A single moment of love is equal to the whole eternity of love.",
    "Never obey anyone's command unless it is coming from within you.",
    "Don't be angry at life — it is not life that is frustrating you, it is you who are not listening to life.",
    "Listen to your being. It is constantly giving you hints; it is a still, small voice.",
    "Remember: nobody is responsible for you. You are totally responsible for yourself.",
    "Love is authentic only when it gives freedom.",
    "Celebrate your own uniqueness.",
    "Intelligence is dangerous. Intelligence means you will start thinking for yourself.",
    "A creative person is one who is independent in his existence.",
    "Die each moment so that you can be new each moment.",
    "Mind: a beautiful servant, a dangerous master.",
    "The mind lives in doubt and the heart lives in trust.",
    "Truth is not for the faint-hearted.",
    "Whenever you act according to your own light, there is immense fulfillment, a deep rejoicing.",
    "Your whole idea about yourself is borrowed.",
    "Life exists without rules; games cannot be played without rules.",
    "Love is happy when it is able to give something. The ego is happy when it is able to take something.",
    "Enlightenment is the understanding that this is all that is, that this is perfect.",
    "If you love a flower, don’t pick it up. Because if you pick it up it dies and it ceases to be what you love.",
    "You cannot be truthful if you are not courageous. You cannot be loving if you are not courageous.",
    "Millions of people are suffering: they want to be loved but they don’t know how to love.",
    "Love needs no reason; love simply is.",
    "Each moment you are fresh, each moment you are new.",
    "Become more and more innocent, less knowledgeable, and more childlike.",
    "The real question is not whether life exists after death. The real question is whether you are alive before death.",
    "Find ecstasy within yourself.",
    "Friendship is the purest love.",
    "Creativity is the greatest rebellion in existence.",
    "The moment you accept yourself, you become beautiful.",
    "If you want to learn anything, learn trust – nothing else is needed.",
    "A mind that is afraid to travel into the unknown will never find the truth.",
    "Life is a mirror, it reflects your face.",
    "Respect life, revere life. There is nothing more holy than life.",
    "Accept yourself, love yourself, and keep moving forward.",
    "Meditation is nothing but a way to be free of all your conditioning.",
    "Don't seek, don't search, don't ask, don't knock, don't demand – relax.",
    "The mind lives in doubt and the heart lives in trust.",
    "Life repeats itself mindlessly – unless you become mindful, it will go on repeating.",
    "Joy is spiritual.",
    "Life is not a problem to be solved; it is a mystery to be lived.",
    "Life is not going to wait for you.",
    "This moment is all there is.",
    "The way of love is the way of no-expectation.",
    "If you love a person, you accept the total person.",
    "Life has to be lived, not controlled.",
    "Don't search for heaven and hell in the future.",
    "You are truth. You are love. You are bliss. You are freedom.",
    "Suffering is a byproduct of unconsciousness.",
    "Be realistic: Plan for a miracle.",
    "Each moment is tremendously precious.",
    "You will be exactly as happy as you decide to be.",
    "Don’t wait for perfection, start embracing each flaw with love.",
    "A person who is centered within is beyond defeat.",
    "Love is life, love is joy.",
    "Don’t compare yourself with others. You are unique.",
    "An alive person has to think for himself.",
    "Real love exists only when there is no jealousy.",
    "You are not accidental. The world needs you.",

    "You have the right to perform your prescribed duties, but you are not entitled to the fruits of your actions.",
    "The mind is everything. What you think you become.",
    "A person is said to be established in self-realization and is called a yogi when he is fully satisfied by virtue of transcendental knowledge and wisdom.",
    "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
    "In the end, the only thing you will regret is the chances you didn’t take.",
    "You came empty-handed, and you will leave empty-handed.",
    "The soul is neither born, nor does it die; it is eternal and indestructible.",
    "There is neither happiness nor sadness in this world; everything is the result of your actions.",
    "Perform your duty equipoised, O Arjuna, abandoning all attachment to success or failure.",
    "To attain success, you must first believe in yourself.",
    "What is to give light must endure burning.",
    "You can’t do anything without the help of others; be humble and take help.",
    "As a man thinks, so he becomes.",
    "He who has no faith in himself can never have faith in God.",
    "Pleasure and pain, gain and loss, victory and defeat—these are the dualities of life.",
    "The only way you can truly be at peace is by relinquishing your desire for recognition.",
    "Do not dwell in the past; do not dream of the future, concentrate the mind on the present moment.",
    "Life is a battle, and you must fight.",
    "The truth is not for the one who is not prepared to endure the consequences.",
    "What you think, you become. What you feel, you attract. What you imagine, you create.",
    "Your only limit is you.",
    "Change is the law of the universe.",
    "Truth alone triumphs; not untruth.",
    "Let go of the past and do not worry about the future.",
    "One who is unattached to the external world can truly enjoy life.",
    "Wisdom is knowing the right path to take; integrity is taking it.",
    "Your actions should be guided by your values.",
    "Harmony in the mind is the first step to success.",
    "Your outer world is a reflection of your inner world.",
    "Every obstacle is a stepping stone towards success.",
    "The present moment is your point of power.",
    "Be aware of your thoughts, for they will create your destiny.",
    "The true essence of the self is beyond fear and doubt.",
    "The world is full of choices; choose wisely.",
    "True strength lies in keeping your heart and mind open.",
    "Face your fears; they are merely illusions.",
    "Joy is the natural state of the soul.",
    "Learn to see the divine in every living being.",
    "Service to others is the greatest service of all.",
    "To love and be loved is the greatest gift of life.",
    "The journey of a thousand miles begins with a single step.",
    "Keep your thoughts positive, as they will create your reality.",
    "The mind is a great servant but a terrible master.",
    "Be the change you wish to see in the world.",
    "Every experience is an opportunity for learning.",
    "Find balance in all things.",
    "Forgiveness is the fragrance of the flower that grows on the tree.",
    "Life is a mirror; it reflects what you are.",
    "Sow seeds of kindness, and they will grow.",
    "The power of love is greater than the power of fear.",
    "Everything in life is a lesson; learn from it.",
    "The path of selfless service is the path of love.",
    "Detach from the outcome; focus on the action.",
    "The greatest wealth is to live content with little.",
    "Happiness is not something you postpone for the future; it is something you design for the present.",
    "Your thoughts create your reality; think wisely.",
    "Desire is the root of all suffering; learn to manage it.",
    "Life is a gift; cherish every moment.",
    "Seek knowledge and wisdom; they are the true treasures.",
    "The more you give, the more you receive.",
    "Breathe, and let go of the past.",
    "Believe in yourself; you are stronger than you think.",
    "Live in the moment; it is all we truly have.",
    "Surrender is not weakness; it is strength in acceptance.",
    "Kindness is the language which the deaf can hear and the blind can see.",
    "Realize that you are not alone in this journey.",
    "Patience is the companion of wisdom.",
    "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
    "You attract what you are; be the best version of yourself.",
    "What you seek is seeking you.",
    "The soul is eternal; it transcends the physical realm.",
    "True happiness comes from within; nurture your inner self.",
    "Life is a series of choices; make them wisely.",
    "Courage is not the absence of fear but the triumph over it.",
    "Hope is the anchor of the soul.",
    "True love knows no boundaries.",
    "In the face of adversity, maintain your inner peace.",
    "You are not a drop in the ocean; you are the entire ocean in a drop.",
    "Every day may not be good, but there is something good in every day.",
    "You are the creator of your destiny; take charge.",
    "Embrace change; it is the essence of life.",
    "Your beliefs shape your reality; choose them wisely.",
    "True joy comes from serving others.",
    "Every moment is a fresh beginning.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The greatest service is to inspire others to serve.",
    "Each day is a new opportunity to grow and evolve.",
    "Love is the bridge between you and everything.",
    "You are what you believe you are.",
    "Let your heart be your compass.",
    "Life is not about finding yourself; it's about creating yourself.",
    "Do what you can, with what you have, where you are.",
    "Your life is your message to the world; make it inspiring.",
    "Everything you can imagine is real.",
    "In the middle of difficulty lies opportunity.",
    "Live as if you were to die tomorrow; learn as if you were to live forever.",
    "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
    "You are the artist of your own life; don’t hand the paintbrush to anyone else.",
    "Trust the timing of your life.",
    "Love all, serve all.",
    "The universe is change; our life is what our thoughts make it.",
    "The only way to do great work is to love what you do.",
    "You are never too old to set another goal or to dream a new dream.",
    "The key to happiness is letting each situation be what it is.",
    "Forgive others not because they deserve forgiveness, but because you deserve peace.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Act without expectation.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "You can’t start the next chapter of your life if you keep re-reading the last one.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Sometimes you will never know the value of a moment until it becomes a memory.",
    "Believe in the magic within you.",
    "Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain."
];

let currentQuoteIndex = Math.floor(Math.random() * oshoQuotes.length);

function displayQuote() {
    const quoteElement = document.getElementById("t1");
    quoteElement.innerHTML = `"${oshoQuotes[currentQuoteIndex]}"`;
}

function nextQuote() {
    currentQuoteIndex = (currentQuoteIndex + 1) % oshoQuotes.length;
    displayQuote();
}

function previousQuote() {
    currentQuoteIndex = (currentQuoteIndex - 1 + oshoQuotes.length) % oshoQuotes.length;
    displayQuote();
}

window.onload = () =>{
 
    displayQuote();


} 