const wq=[ 
    "What other people think of you is none of your business.",
    "Your worth isn’t determined by other people’s opinions.",
    "The only opinion that truly matters is your own.",
    "Don’t let the noise of others’ opinions drown out your inner voice.",
    "The best way to gain self-confidence is to do what you are afraid to do.",
    "What others think of you is a reflection of their own reality, not yours.",
    "You can't control how others see you, but you can control how you see yourself.",
    "Live your life and forget your age.",
    "Be yourself; everyone else is already taken.",
    "Don't let someone else's opinion of you become your reality.",
    "You are unique and valuable, regardless of others' perceptions.",
    "Stop letting people who do so little for you control so much of your mind, feelings, and emotions.",
    "Your life is yours alone; don’t let others dictate how you should live it.",
    "The greatest prison people live in is the fear of what other people think.",
    "Your happiness is not dependent on other people's approval.",
    "The people who care about you will love you for who you are.",
    "What you think of yourself is far more important than what others think of you.",
    "Success is not about what you have, but about who you are.",
    "Doubt kills more dreams than failure ever will.",
    "Your value doesn't decrease based on someone else's inability to see your worth.",
    "You are not a drop in the ocean. You are the entire ocean in a drop.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "It's not the load that breaks you down; it's how you carry it.",
    "Take pride in how far you've come and have faith in how far you can go.",
    "Life is too short to waste time on things that don’t matter.",
    "The only limits that exist are the ones you create.",
    "People will always have opinions; make sure they don’t hold you back.",
    "Choose to be authentic; it’s the best form of rebellion.",
    "Your opinion of yourself is what matters most.",
    "The world is full of critics. Be your own best advocate.",
    "Focus on what you can control, and let go of what you cannot.",
    "Comparison is the thief of joy.",
    "Happiness comes when you stop comparing yourself to others.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Don't let the fear of what others think stop you from being yourself.",
    "The truth is that everyone has their own opinions, and they often have nothing to do with you.",
    "Be a voice, not an echo.",
    "Believe in yourself and all that you are.",
    "Self-acceptance is the key to true happiness.",
    "Do not wait for someone else to come and speak for you. It's you who can change the world.",
    "The most important thing is to enjoy your life—to be happy. It’s all that matters.",
    "Your value is not in how others perceive you but in how you perceive yourself.",
    "Live for you, not for others.",
    "You don’t need anyone’s approval to be who you are.",
    "Be proud of who you are and not ashamed of how others see you.",
    "You are not defined by your past; you are prepared by your past.",
    "The only way to do great work is to love what you do.",
    "Sometimes, the hardest thing and the right thing are the same.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Be yourself, even if you’re not sure who that is yet.",
    "You are worthy of love and respect just as you are.",
    "Don’t let your past mistakes define your future.",
    "You are allowed to be both a masterpiece and a work in progress.",
    "Stand up for what you believe in, even if it means standing alone.",
    "Don't let others' opinions create a prison for you.",
    "Your journey is your own; embrace it.",
    "Confidence comes from not only knowing who you are but also accepting it.",
    "Sometimes you will never know the value of a moment until it becomes a memory.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Believe you can, and you're halfway there.",
    "No one can make you feel inferior without your consent.",
    "People will always judge you, but they can’t change who you are.",
    "Live your truth and let others live theirs.",
    "Don’t take criticism from someone you wouldn’t take advice from.",
    "You have the power to create your own reality.",
    "Let your life be your message to the world.",
    "Your opinions of yourself should matter more than those of others.",
    "Don't let the fear of rejection keep you from living authentically.",
    "It’s better to be disliked for being who you are than liked for being someone you’re not.",
    "The greatest risk is not taking one at all.",
    "Your past does not determine your future.",
    "Be the author of your own story.",
    "Everyone has an opinion; what matters is how you feel about yourself.",
    "You are enough just as you are.",
    "Don’t let people who don’t know your journey dictate your worth.",
    "You are not what happened to you; you are what you choose to become.",
    "The strongest people are not those who show strength in front of us but those who win battles we know nothing about.",
    "You don’t need permission to live a life true to yourself.",
    "Let go of the need for validation from others.",
    "No one knows you better than you know yourself.",
    "Trust yourself and your instincts.",
    "Do not dwell in the past; do not dream of the future. Concentrate the mind on the present moment.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "The more you love your own decisions, the less you need others to love them.",
    "Stop worrying about what others think; your life is your own to live.",
    "You have the right to be yourself and express who you truly are.",
    "Find your own path and walk it with confidence.",
    "Let your confidence shine and drown out the negativity.",
    "Surround yourself with those who uplift you.",
    "Your self-worth is determined by you. You don’t have to depend on someone telling you who you are.",
    "You don’t need to be perfect to be amazing.",
    "Don’t change so people will like you. Be yourself and the right people will love the real you.",
    "Your opinion is the most important opinion.",
    "When you realize your worth, you’ll stop giving discounts.",
    "Don’t let others’ opinions control your happiness.",
    "You are stronger than you think.",
    "Live life on your own terms.",
    "What you think of yourself is what you will become.",
    "Trust yourself, you know more than you think you do.",
    "You are not what others think you are; you are what you think you are.",
    "Keep your head up, and your heart strong.",
    "It’s not about being perfect; it’s about being true to yourself.",
    "When you stop trying to impress others, you can start to live authentically.",
    "Your journey may be different, but that doesn't mean it's less valid.",
    "People will judge you regardless; choose to live for yourself.",
    "Stop worrying about fitting in; you were born to stand out.",
    "The moment you stop worrying about what others think is the moment you find yourself.",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "Don’t waste your time trying to impress others.",
    "You are not alone in feeling this way; many people struggle with self-acceptance.",
    "Forgive yourself for past mistakes and keep moving forward.",
    "The opinions of others can be loud, but your inner voice should be louder.",
    "Embrace your uniqueness; it’s what makes you special.",
    "Life is too short to spend it being someone you’re not.",
    "You define your own worth.",
    "Be proud of who you are and how far you’ve come.",
    "Believe in your abilities, and others will too.",
    "You are allowed to take up space.",
    "Confidence is not 'they will like me.' Confidence is 'I’ll be fine if they don’t.'",
    "Your self-worth is not tied to your performance or productivity.",
    "Be a rainbow in someone else's cloud.",
    "Don’t compare yourself to others; comparison is the thief of joy.",
    "You don’t have to have it all figured out to move forward.",
    "Let your heart be your compass.",
    "The most important relationship is the one you have with yourself.",
    "Your authenticity is your greatest strength.",
    "Focus on your own journey; it’s the only one that matters.",
    "You can’t please everyone, and that’s perfectly okay.",
    "Let go of the need for approval; it will set you free.",
    "Your heart knows what it needs; trust it.",
    "Success is not defined by others; it’s defined by you.",
    "The less you care about what people think, the happier you’ll be.",
    "You are worth more than your mistakes.",
];

let currentIndex = Math.floor(Math.random() * wq.length); // Set a random index on load

function displayQuote() {
    const quoteElement = document.getElementById('t1');
    if (quoteElement) {
        quoteElement.innerHTML = `"${wq[currentIndex]}"`;
    }
}

function nextQuote() {
    currentIndex = (currentIndex + 1) % wq.length;
    displayQuote();
}

function previousQuote() {
    currentIndex = (currentIndex - 1 + wq.length) % wq.length;
    displayQuote();
}

// Corrected window.onload to display a random quote initially
window.onload = () => {
    displayQuote();
};